# Oh My Zsh: Managed as an external to keep the bootstrap script light
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1

[".oh-my-zsh/custom/plugins/zsh-bat"]
    type = "archive"
    url = "https://github.com/fdellwing/zsh-bat/archive/master.tar.gz"
    exact = true
    stripComponents = 1

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1

[".oh-my-zsh/custom/completions/_bazel"]
    type = "file"
    url = "https://raw.githubusercontent.com/bazelbuild/bazel/master/scripts/zsh_completion/_bazel"

[".local/bin/buildifier"]
    type = "file"
    url = "https://github.com/bazelbuild/buildtools/releases/latest/download/buildifier-linux-amd64"
    executable = true
